### ISSUE TITLE
Error when toggling backprop view

### ISSUE THREAD

**Issue by smcallis** [yosinski/deep-visualization-toolbox#11]
I get this when I try to toggle between fordward activations and backprop view:

Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/smcallis/tmp/deep-visualization-toolbox/caffevis/app.py", line 158, in run
    self.net.backward_from_layer(backprop_layer, diffs, zero_higher = True)
AttributeError: 'Classifier' object has no attribute 'backward_from_layer'

And then the GUI seems to hang.  I believe I'm on the latest caffe (from github)

**Comment by 201power** [comment]
I got the same error when I try to start the toolbox,
All the activation show black image, not sure why

![untitled](https://cloud.githubusercontent.com/assets/7299296/8808903/32891498-2f9a-11e5-9539-4240f97e4905.png)

**Comment by vincent31** [comment]
Same problem here. I think this issue was fixed in "fooling" but not here in "deep-visualization-toolbox"

**Comment by yosinski** [comment]
@smcallis Can you ensure you're using the deconv-deep-vis-toolbox, as described in Step 0 here: https://github.com/yosinski/deep-visualization-toolbox . The Python bindings in the master branch of caffe don't enable arbitrary backprop and deconv.

**Comment by smcallis** [comment]
@yosinski Sure enough removing caffe and rebuilding from that branch seems to have fixed the problem for me.

**Comment by FredaZhang338** [comment]
@yosinski @smcallis excuse me, I met the same problem, I compiled the master branch of caffe as step 0 said, then under this dirctory(caffe root), I follwed the instructions on step 1, and it said that i have already switched to a new branch'yosinski/deconv-deep-vis-toolbox'. And I installed all the requisites. When I run ./too_box.py I can get the window but I cannot  toggle between fordward activations and backprop view: I got the same error, it made me confused, can you help me to fix it? thx a lot~
