### ISSUE TITLE
Imput Image size error

### ISSUE THREAD

**Issue by ming1144** [yosinski/deep-visualization-toolbox#130]
I want to use deepVis to show my result

but somthing wrong so I can't use 

below is my log

  File "D:\Python27_1_11\lib\threading.py", line 801, in __bootstrap_innerself.run()
  File "K:\deep-visualization-toolbox\caffevis\caffe_proc_thread.py", line 85, in run
    net_preproc_forward(self.net, im_small, self.input_dims)
  File "K:\deep-visualization-toolbox\caffevis\caffevis_helper.py", line 9, in net_preproc_forward
    assert img.shape == appropriate_shape, 'img is wrong size (got %s but expected %s)' % (img.shape, appropriate_shape)AssertionError: img is wrong size (got (512L, 256L, 3L) but expected (256L, 512L, 3))

my network and model are here
https://drive.google.com/drive/folders/0B9NQg0N2VYD6aE5BSTFDVW42TVk?usp=sharing

**Comment by arikpoz** [comment]
@ming1144 
I've substantially refactored the tool, fixed many bugs, among them the tool ability to work on rectangular inputs instead of squares

Latest version is in https://github.com/arikpoz/deep-visualization-toolbox

**Comment by ming1144** [comment]
@arikpoz 
Thanks for your answer
even though I have finished the problem by other's report

but still thanks to your contribution
I will try your verision later
