### ISSUE TITLE
RuntimeError: Could not open file ....../deep-visualization-toolbox/./models/caffenet-yos/caffenet-yos-weights

### ISSUE THREAD

**Issue by asmaabenbouna** [yosinski/deep-visualization-toolbox#145]
hello, I found your work very interesting, so I chose it to test it in our model on my internship. 
Also, it's my first time I use Caffe with deep learning.
I use the improved version of arikpoz
When I'm trying to compile in CPU mode after modifying  caffevis_mode_gpu in sittings.py by False:
caffevis_mode_gpu = locals().get('caffevis_mode_gpu', False)
i got some error that i don't understand it:
![capture du 2018-06-06 16-39-21](https://user-images.githubusercontent.com/39764724/41045476-cc7ba62e-69a8-11e8-86b7-c804763ad209.png)

Thank you !

**Comment by Black-Eyes-SGC** [comment]
You have a problem with your path.It should not be a technical problem，Check the path carefully。




------------------ 原始邮件 ------------------
发件人: "AsmaaBenn"<notifications@github.com>;
发送时间: 2018年6月6日(星期三) 晚上10:51
收件人: "yosinski/deep-visualization-toolbox"<deep-visualization-toolbox@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: [yosinski/deep-visualization-toolbox] RuntimeError: Could not openfile....../deep-visualization-toolbox/./models/caffenet-yos/caffenet-yos-weights(#145)




hello, I found your work very interesting, so I chose it to test it in our model on my internship.
 Also, it's my first time I use Caffe with deep learning.
 I use the improved version of arikpoz
 When I'm trying to compile in CPU mode after modifying  caffevis_mode_gpu in sittings.py by False:
 caffevis_mode_gpu = locals().get('caffevis_mode_gpu', False)
 i got some error that i don't understand it:
 
 
Thank you !

**Comment by asmaabenbouna** [comment]
thank you for your help.
I thought in the arikpoz version the Per-unit visualizations are downloaded automatically.
solution as motioned in the old version : 
$ cd models/caffenet-yos/
$ ./fetch.sh all (fc6/fc7)
