### ISSUE TITLE
unable to compile, repo doesn't exist

### ISSUE THREAD

**Issue by n3011** [yosinski/deep-visualization-toolbox#19]
this repositories doesnt exist , unable to compile
git remote add yosinski https://github.com/yosinski/caffe.git
$ git fetch --all
$ git checkout --track -b deconv-deep-vis-toolbox yosinski/deconv-deep-vis-toolbox
$ make clean

**Comment by bairdzhang** [comment]
Hi, I tried again and didn't meet your problem. Maybe you need to clone the original caffe first and then work under the caffe directory?

**Comment by fabioperez** [comment]
@bairdzhang is right, first you have to clone Caffe:

    git clone https://github.com/BVLC/caffe.git

Then run the other commands.

**Comment by yosinski** [comment]
Looks like this is resolved. Closing for now; reopen if needed.
