### ISSUE TITLE
python-opencv dependency

### ISSUE THREAD

**Issue by lukeyeager** [yosinski/deep-visualization-toolbox#2]
To use this tool, you must have `python-opencv` installed. Otherwise you get this error: 
```
Error: Could not import cv2, please install it first.
Traceback (most recent call last):
  File "./run_toolbox.py", line 3, in <module>
    from core import LiveVis
  File "/home/lyeager/code/deep-visualization-toolbox/core.py", line 14, in <module>
    import cv2
ImportError: No module named cv2
```
That package [isn't required](https://github.com/BVLC/caffe/blob/master/python/requirements.txt) for caffe, so you should mention it in your installation instructions.

I installed it with `sudo apt-get install python-opencv`, but you could probably install it with pip if you preferred.

**Comment by yosinski** [comment]
Hi @lukeyeager, thanks for filing the issue, and sorry for the delayed response (I was at CVPR last week). I'll add this to the documentation.

**Comment by isalirezag** [comment]
I did what you mentioned in step 2 (sudo apt-get install python-opencv) but I still received the same error.
I appreciate it if you can help please.
Is there any way that I can check to make sure that I did it write?
