### ISSUE TITLE
Issue downloading example model weights and visualizations

### ISSUE THREAD

**Issue by Deepak-** [yosinski/deep-visualization-toolbox#24]
Hi guys,

When I try to run this code:

`$ cd models/caffenet-yos/`
`$ ./fetch.sh`

 I am greeted with a 404 error. Any help?

Thanks!

**Comment by yosinski** [comment]
The server is still up and seems to be working for me. Can you replace the first line of `fetch.sh` with this

    #!/usr/bin/env bash -x

and rerun the script and paste the output here?

**Comment by tanelp** [comment]
I have the same issue.

Changing shebang to `#!/usr/bin/env bash -x` doesn't work. It prompts `"No such file or directory"` because a shebang line can have at most one argument.

Anyway, I get the following output running `fetch.sh` in debug mode:

```
$ ./fetch.sh
+ fetch_file http://c.yosinski.com/ caffenet-yos-weights
+ url_base=http://c.yosinski.com/
+ filename=caffenet-yos-weights
+ url=http://c.yosinski.com//caffenet-yos-weights
+ '[' -e caffenet-yos-weights ']'
+ echo 'http://c.yosinski.com//caffenet-yos-weights: fetching...'
http://c.yosinski.com//caffenet-yos-weights: fetching...
+ wget http://c.yosinski.com//caffenet-yos-weights
--2015-11-16 10:59:05--  http://c.yosinski.com//caffenet-yos-weights
Resolving c.yosinski.com (c.yosinski.com)... 50.63.202.76
Connecting to c.yosinski.com (c.yosinski.com)|50.63.202.76|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-11-16 10:59:06 ERROR 404: Not Found.
```

**Comment by Deepak-** [comment]
Yes, I too get `"No such file or directory"` when I change the first line to `#!/usr/bin/env bash -x`.
However, now when I change it back to  `#!/usr/bin/env bash`, it keeps hanging:

`http://c.yosinski.com//caffenet-yos-weights: fetching...
--2015-11-16 13:19:53--  http://c.yosinski.com//caffenet-yos-weights
Resolving c.yosinski.com (c.yosinski.com)... 50.63.202.76
Connecting to c.yosinski.com (c.yosinski.com)|50.63.202.76|:80... connected.
HTTP request sent, awaiting response... `

**Comment by yosinski** [comment]
Oops, it was a DNS issue; thanks for reporting this!

I believe the relevant pointers are now correct. Can you try again and see if it works for you now?

**Comment by Deepak-** [comment]
Yep its working  :)

Thanks for the quick response!

**Comment by yosinski** [comment]
@Deepak- Glad to hear!

I'll close this for now. @tanelp: feel free to reopen if it's not resolved for you as well.
