### ISSUE TITLE
OpenCV Error

### ISSUE THREAD

**Issue by rfarouni** [yosinski/deep-visualization-toolbox#29]
Hi,

I have an anaconda installed and I am able to import cv2  from Python, but when I run  ./run_toolbox.py, I get the following error:

> Runningtoolbox. Push h for help or q to quit.
OpenCV` Error: Unspecified error (The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script) in cvNamedWindow, file -------src-dir-------/opencv-2.4.10/modules/highgui/src/window.cpp, line 483
Traceback (most recent call last):
  File "./run_toolbox.py", line 29, in <module>
    main()
  File "./run_toolbox.py", line 24, in main
    lv.run_loop()
  File "/home/rick/Documents/deep-visualization-toolbox/core.py", line 309, in run_loop
    self.init_window()
  File "/home/rick/Documents/deep-visualization-toolbox/core.py", line 266, in init_window
    cv2.namedWindow(self.window_name)
cv2.error: -------src-dir-------/opencv-2.4.10/modules/highgui/src/window.cpp:483: error: (-2) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function cvNamedWindow

**Comment by yosinski** [comment]
Hi Rick, I haven't seen this problem before, so my best guess at a fix is
to follow the instructions mentioned in the error message.

Let us know if that fixes it!



jason

~ painstakingly composed and sent from my phone
---------------------------
Jason Yosinski, Cornell Computer Science Ph.D. candidate
http://yosinski.com/     +1.719.440.1357

**Comment by rfarouni** [comment]
I actually have followed the instructions but that didn't help. What solved the problem though is installing opencv-2.4.11 from a custom channel (e.g. menpo) on  Anaconda.org public repository. 

`conda remove opencv `
`conda update conda`
`conda install --channel  menpo opencv `

**Comment by yosinski** [comment]
Glad to hear; closing issue.
