### ISSUE TITLE
Linking errors when building pycaffe on caffe branch 'deconv-deep-vis-toolbox'

### ISSUE THREAD

**Issue by yrevar** [yosinski/deep-visualization-toolbox#32]
I am using OSX El Capitan 10.11.2 system. I followed caffe build step carefully, and on caffe master branch I could build libcaffe as well as pycaffe with no issue; also tried a couple of sample which seems to work well. However, on deconv-deep-vis-toolbox branch I always get following error: 
```bash
Undefined symbols for architecture x86_64:
  "caffe::Net<float>::DeconvFromTo(int, int)", referenced from:
      caffe::init_module__caffe() in _caffe-c1a51b.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
I am using the same Makefile and configs on this branch. I am pasting the final compiler command if you could figure out what's wrong. I am still trying to debug what's causing it. 

```bash
/usr/bin/clang++ -shared -o python/caffe/_caffe.so python/caffe/_caffe.cpp \
		-o python/caffe/_caffe.so -pthread -fPIC -DCAFFE_VERSION=1.0.0-rc3 -DGTEST_USE_OWN_TR1_TUPLE=1 -DNDEBUG -O2 -DUSE_OPENCV -DUSE_LEVELDB -DUSE_LMDB -DCPU_ONLY -I/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/lib/python2.7/site-packages/numpy/core/include -I/usr/local/include -I.build_release/src -I./src -I./include -I/System/Library/Frameworks/Accelerate.framework/Versions/Current/Frameworks/vecLib.framework/Headers/ -Wall -Wno-sign-compare -lcaffe -framework Accelerate -L/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib -L/usr/local/lib -L/usr/lib -L.build_release/lib  -lglog -lgflags -lprotobuf -lboost_system -lboost_filesystem -lm -lhdf5_hl -lhdf5 -lleveldb -lsnappy -llmdb -lopencv_core -lopencv_highgui -lopencv_imgproc -lboost_thread-mt -lcblas -lboost_python -lpython2.7 \
		-Wl,-rpath,@loader_path/../../build/lib
touch python/caffe/proto/__init__.py
echo PROTOC \(python\) src/caffe/proto/caffe.proto
protoc --proto_path=src/caffe/proto --python_out=python/caffe/proto src/caffe/proto/caffe.proto 
```

As I mentioned, the same command works on caffe master branch. I could build libcaffe as well as pycaffe. But, on deepvis branch pycaffe build fails with linking error mentioned above, so I believe there's some issue in previous step, i.e. building libcaffe.so. It might be missing some dependencies related to Deconvolution Layers. 

Looking forward to some quick help. Thanks in advance!

**Comment by yosinski** [comment]
Hmm...

Can you try running
    make clean superclean
first? E.g. try to compile the deconv-dep-vis-toolbox branch using
    git checkout deconv-dep-vis-toolbox
    git pull
    make clean superclean
    make -j
    make pycaffe

**Comment by yrevar** [comment]
I have already tried this exercise a few times before, did it one more time but no luck. Same output 
```bash
$ make -j pycaffe
touch python/caffe/proto/__init__.py
CXX/LD -o python/caffe/_caffe.so python/caffe/_caffe.cpp
PROTOC (python) src/caffe/proto/caffe.proto
python/caffe/_caffe.cpp:210:1: warning: unused typedef 'assertion' [-Wunused-local-typedef]
BOOST_PYTHON_MEMBER_FUNCTION_OVERLOADS(SolveOverloads, Solve, 0, 1);
^
/usr/local/include/boost/python/detail/defaults_gen.hpp:375:5: note: expanded from macro 'BOOST_PYTHON_MEMBER_FUNCTION_OVERLOADS'
    BOOST_PYTHON_GEN_MEM_FUNCTION_STUB(                                                     \
    ^
/usr/local/include/boost/python/detail/defaults_gen.hpp:276:9: note: expanded from macro 'BOOST_PYTHON_GEN_MEM_FUNCTION_STUB'
        BOOST_PYTHON_OVERLOAD_CONSTRUCTORS(fstubs_name, n_args + 1, n_dflts)            \
        ^
/usr/local/include/boost/python/detail/defaults_gen.hpp:216:46: note: expanded from macro 'BOOST_PYTHON_OVERLOAD_CONSTRUCTORS'
                N,n_args>::too_many_keywords assertion;                                     \
                                             ^
python/caffe/_caffe.cpp:210:1: warning: unused typedef 'assertion' [-Wunused-local-typedef]
/usr/local/include/boost/python/detail/defaults_gen.hpp:375:5: note: expanded from macro 'BOOST_PYTHON_MEMBER_FUNCTION_OVERLOADS'
    BOOST_PYTHON_GEN_MEM_FUNCTION_STUB(                                                     \
    ^
/usr/local/include/boost/python/detail/defaults_gen.hpp:276:9: note: expanded from macro 'BOOST_PYTHON_GEN_MEM_FUNCTION_STUB'
        BOOST_PYTHON_OVERLOAD_CONSTRUCTORS(fstubs_name, n_args + 1, n_dflts)            \
        ^
/usr/local/include/boost/python/detail/defaults_gen.hpp:225:46: note: expanded from macro 'BOOST_PYTHON_OVERLOAD_CONSTRUCTORS'
                N,n_args>::too_many_keywords assertion;                                     \
                                             ^
2 warnings generated.
Undefined symbols for architecture x86_64:
  "caffe::Net<float>::DeconvFromTo(int, int)", referenced from:
      caffe::init_module__caffe() in _caffe-ab3341.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [python/caffe/_caffe.so] Error 1
```
I didn't paste these warnings before, as I see them with normal build too.

**Comment by yosinski** [comment]
To make sure we're looking at the same code, can you run these two commands?

```
[~/s/caffe2] $ git rev-parse HEAD
20a81e503c4a0e7806df074463a321ba897f2a53

[~/s/caffe2] $ find -L .  -path '*/.git' -prune -o -type f -print | xargs -I {} grep -E -IinH deconvfromto {}
./include/caffe/net.hpp:81:  void DeconvFromTo(int start, int end);
./python/caffe/_caffe.cpp:231:    .def("_deconv", &Net<Dtype>::DeconvFromTo)
./src/caffe/net.cpp:648:void Net<Dtype>::DeconvFromTo(int start, int end) {
./src/caffe/net.cpp:835:  DeconvFromTo(start, 0);
./src/caffe/net.cpp:840:  DeconvFromTo(layers_.size() - 1, end);
./src/caffe/net.cpp:845:  DeconvFromTo(layers_.size() - 1, 0);
```

**Comment by yrevar** [comment]
Yes it is. I did check source files when at first I suspected missing functions, Deconv layers and Caffe Net entries are there. 
```bash
git rev-parse HEAD
20a81e503c4a0e7806df074463a321ba897f2a53

find -L .  -path '*/.git' -prune -o -type f -print | xargs -I {} grep -E -IinH deconvfromto {}
./include/caffe/net.hpp:81:  void DeconvFromTo(int start, int end);
./python/caffe/_caffe.cpp:231:    .def("_deconv", &Net<Dtype>::DeconvFromTo)
./src/caffe/net.cpp:648:void Net<Dtype>::DeconvFromTo(int start, int end) {
./src/caffe/net.cpp:835:  DeconvFromTo(start, 0);
./src/caffe/net.cpp:840:  DeconvFromTo(layers_.size() - 1, end);
./src/caffe/net.cpp:845:  DeconvFromTo(layers_.size() - 1, 0); 

nm -g .build_release/lib/libcaffe.so.1.0.0-rc3  | grep DeconvFromTo
00000000001125c0 T __ZN5caffe3NetIdE12DeconvFromToEii
0000000000107030 T __ZN5caffe3NetIfE12DeconvFromToEii
```

**Comment by yosinski** [comment]
Well I'm somewhat stumped. DeconvFromTo is based on BackwardFromTo and is mentioned in the same places of the same files:

```
[~/s/caffe2] $ find -L .  -path '*/.git' -prune -o -type f -print | xargs -I {} grep -E -IinH BackwardFromTo {}
./include/caffe/net.hpp:73:  void BackwardFromTo(int start, int end);
./python/caffe/_caffe.cpp:230:    .def("_backward", &Net<Dtype>::BackwardFromTo)
./src/caffe/net.cpp:635:void Net<Dtype>::BackwardFromTo(int start, int end) {
./src/caffe/net.cpp:806:  BackwardFromTo(start, 0);
./src/caffe/net.cpp:811:  BackwardFromTo(layers_.size() - 1, end);
./src/caffe/net.cpp:816:  BackwardFromTo(layers_.size() - 1, 0);

[~/s/caffe2] $ find -L .  -path '*/.git' -prune -o -type f -print | xargs -I {} grep -E -IinH DeconvFromTo {}
./include/caffe/net.hpp:81:  void DeconvFromTo(int start, int end);
./python/caffe/_caffe.cpp:231:    .def("_deconv", &Net<Dtype>::DeconvFromTo)
./src/caffe/net.cpp:648:void Net<Dtype>::DeconvFromTo(int start, int end) {
./src/caffe/net.cpp:835:  DeconvFromTo(start, 0);
./src/caffe/net.cpp:840:  DeconvFromTo(layers_.size() - 1, end);
./src/caffe/net.cpp:845:  DeconvFromTo(layers_.size() - 1, 0);
```

So I can see no reason why one symbol (BackwardFromTo) is included in the object file and one isn't (DeconvFromTo) from 

Can you try CPU_ONLY mode if you haven't, just to check if that works?

Can you make doubly certain you're compiling from scratch?

```
[~/s/caffe2] $ make clean superclean
No generated files found.

[~/s/caffe2] $ git status --ignored
On branch deconv-deep-vis-toolbox
Your branch is up-to-date with 'origin/deconv-deep-vis-toolbox'.

Ignored files:
  (use "git add -f <file>..." to include in what will be committed)

	Makefile.config
```

You can compare to my [Makefile.config](https://gist.github.com/yosinski/a5111163dba7b98032b3) if you want, though of course some details may differ. Make sure you're not adding/hardcoding any paths in your Makefile.config to other Caffe checkouts you may have around.

**Comment by yrevar** [comment]
It's certainly a strange issue. I am using CPU_ONLY mode, no NVIDIA GPUs on my machine. Looking at your config quickly I can see some differences (atlas vs open blas, python 2.7.10_2 vs 2.7.9, explicit boost include lib paths), but nothing seems to cause this error. Here's my [Makefile.config](https://gist.github.com/yrevar/ca181cd78136dd1d2391) if you'd like to verify. 
```bash
yrevar @ caffe $ git status --ignored
On branch deconv-deep-vis-toolbox
Your branch is up-to-date with 'yosinski/deconv-deep-vis-toolbox'.
Ignored files:
  (use "git add -f <file>..." to include in what will be committed)

	Makefile.config
	examples/.ipynb_checkpoints/
	models/bvlc_reference_caffenet/bvlc_reference_caffenet.caffemodel

nothing to commit, working directory clean
```

**Comment by yosinski** [comment]
Have you ever "installed" Caffe to some system-wide location, e.g. put a `libcaffe.so` somewhere that it would be found by your final linking command? If so, it could be masking the local `libcaffe.so` that should be used.

**Comment by yrevar** [comment]
Ohh yes! libcaffe was actually present on a system-wide location; deleting it fixes this issue. I should have checked this possibility before. I guess, we need something like 'make superduper clean', haha :-) 

Appreciate your help, Thanks so much :+1:

**Comment by yrevar** [comment]
It's super cool!  <img src="http://imgur.com/4lPjAyt"></img>

Closing this issue.

**Comment by yosinski** [comment]
Glad to hear it's working!

And perhaps others that have installed Caffe system-wide will find this page and save some time :)

**Comment by empzxb** [comment]
Hi, yosinski
I have the same problem as yrevar

`/usr/local/include/boost/python/detail/defaults_gen.hpp:225:46: note: expanded
from macro BOOST_PYTHON_OVERLOAD_CONSTRUCTORSN,n_args>::too_many_keywords assertion...^16 warnings generated.
Undefined symbols for architecture x86_64:"caffe::Net<float>::DeconvFromTo(int, int)", referenced from:
caffe::init_module__caffe() in _caffe-e735b5.old: 
symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [python/caffe/_caffe.so] Error 1`

and I have delete all the libcaffe.so file and soft link

but the difference is this 

`./include/caffe/net.hpp:81:  void DeconvFromTo(int start, int end);
./python/caffe/_caffe.cpp:231:    .def("_deconv", &Net<Dtype>::DeconvFromTo)
./src/caffe/net.cpp:595:void Net<Dtype>::DeconvFromTo(int start, int end) {
./src/caffe/net.cpp:772:  DeconvFromTo(start, 0);
./src/caffe/net.cpp:777:  DeconvFromTo(layers_.size() - 1, end);
./src/caffe/net.cpp:782:  DeconvFromTo(layers_.size() - 1, 0);`


we are not the same code here


thanks for any idea to solve this problem here

**Comment by empzxb** [comment]
> ./include/caffe/net.hpp:81:  void DeconvFromTo(int start, int end);
./python/caffe/_caffe.cpp:231:    .def("_deconv", &Net<Dtype>::DeconvFromTo)
./src/caffe/net.cpp:595:void Net<Dtype>::DeconvFromTo(int start, int end) {
./src/caffe/net.cpp:772:  DeconvFromTo(start, 0);
./src/caffe/net.cpp:777:  DeconvFromTo(layers_.size() - 1, end);
./src/caffe/net.cpp:782:  DeconvFromTo(layers_.size() - 1, 0);

first time use the system, the word is not easy to see, so I try this format

**Comment by taylorty** [comment]
Hi @yrevar could you please explain how did you delete libcaffe in the system-wide? I have the same issue with you above but don't know how to solve. Thank you so much!
