### ISSUE TITLE
Keypresses not registering

### ISSUE THREAD

**Issue by lukeyeager** [yosinski/deep-visualization-toolbox#4]
>Running loop. Push h for help or q to quit.

When I try to press `h` (or `H` or `Ctrl+H`, etc.), I just get this in the console:
```
...........................................................................Not sure what to do with key 1048680
..............................................Not sure what to do with key 1114081
.................................Not sure what to do with key 1114184
.............................................................Not sure what to do with key 1114083
...Not sure what to do with key 1376235
.......................Not sure what to do with key 5505128
......................................................
```
So I can't really do anything with this tool. Am I missing something obvious? I have a standard keyboard.

**Comment by vimalthilak** [comment]
I noticed similar behavior on my Mac OS X laptop as well.

**Comment by yosinski** [comment]
Thanks for the report; this is unfortunate. @vimalthilak and @lukeyeager: can you pull, run the new `test_keys.py` script, and paste your results here?

**Comment by lukeyeager** [comment]
```
$ ./test_keys.py 
Click on the picture and then carefully push the following keys:
  Press key     j:  code not found: 1048682
  Press key     k:  code not found: 1048683
  Press key     J:  code not found: 1114081
  Press key     K:  code not found: 1114186
  Press key     1:  code not found: 1048625
  Press key     2:  code not found: 1048626
  Press key  left:  code not found: 1113937
  Press key right:  code not found: 1113939
  Press key   esc:  code not found: 1048603
```

It registered `SHIFT+J` as two keystrokes. I never typed `SHIFT+K`.

**Comment by yosinski** [comment]
Thanks, @lukeyeager. For reference, on Mac OS X 10.8 I get the following:

    $ ./test_keys.py
    Click on the picture and then carefully push the following keys:
        Press key     j:  got code 106 = j
        Press key     k:  got code 107 = k
        Press key     J:  got code 74 = J
        Press key     K:  got code 75 = K
        Press key     1:  got code 49 = 1
        Press key     2:  got code 50 = 2
        Press key  left:  got code 63234 = left
        Press key right:  got code 63235 = right
        Press key   esc:  got code 27 = esc

What OS are you using, and what version of OpenCV? If you try the following commands, what numbers are produced?

    $ python
    >>> ord('a')
    97
    >>> ord(u'a')
    97

**Comment by lukeyeager** [comment]
Ubuntu 14.04, OpenCV 2.4.8

```
$ python
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> ord('a')
97
>>> ord(u'a')
97
```

**Comment by yosinski** [comment]
Hmm... so sometimes OpenCV returns the same keycode as Python (e.g. on my Mac setup), but on other systems the two keycodes don't match. @lukeyeager: any ideas for how we could determine in Python the codes that will be returned by your OpenCV for each letter (1048682 for j, etc.)?

**Comment by lukeyeager** [comment]
>  sometimes OpenCV returns the same keycode as Python (e.g. on my Mac setup), but on other systems the two keycodes don't match

That's annoying.

> any ideas for how we could determine in Python the codes that will be returned by your OpenCV for each letter (1048682 for j, etc.)?

[This SO post](http://stackoverflow.com/a/20577067/2404152) looks interesting.

**Comment by yosinski** [comment]
Hey @lukeyeager, I implemented what I hope is a more robust key binding system. For me it works on Mac and Linux (Ubuntu) now. Can you grab the dev branch and try it out? If it doesn't work, can you paste the output of the updated ./test_keys.py?

For reference, I now get the following on Mac:

    $ ./test_keys.py
    Click on the picture and then carefully push the following keys:
      Press key     j:    106 (0x6a) matched j
      Press key     k:    107 (0x6b) matched k
      Press key     J:    74 (0x4a) matched J
      Press key     K:    75 (0x4b) matched K
      Press key     1:    49 (0x31) matched 1
      Press key     2:    50 (0x32) matched 2
      Press key  left:    63234 (0xf702) matched left
      Press key right:    63235 (0xf703) matched right
      Press key   esc:    27 (0x1b) matched esc

And on Ubuntu:
    
    $ ./test_keys.py
    Click on the picture and then carefully push the following keys:
      Press key     j:    1048682 (0x10006a) matched j
      Press key     k:    1048683 (0x10006b) matched k
      Press key     J:  (ignoring modifier leftshift)   1114186 (0x11004a) matched J
      Press key     K:    1114187 (0x11004b) matched K
      Press key     1:    1048625 (0x100031) matched 1
      Press key     2:    1048626 (0x100032) matched 2
      Press key  left:    1113937 (0x10ff51) matched left
      Press key right:    1113939 (0x10ff53) matched right
      Press key   esc:    1048603 (0x10001b) matched esc

**Comment by lukeyeager** [comment]
Getting closer!

Ubuntu 14.04:
```
$ ./test_keys.py 
Click on the picture and then carefully push the following keys:
  Press key     j:    1048682 (0x10006a) matched j
  Press key     k:    1048683 (0x10006b) matched k
  Press key     J:  * 1114081 (0x10ffe1) failed, matched key leftshift (masked vals tried: 65505 (0xffe1), 225 (0xe1))
  Press key     K:  * 1114186 (0x11004a) failed, matched key J (masked vals tried: 74 (0x4a), 74 (0x4a))
  Press key     1:    1048625 (0x100031) matched 1
  Press key     2:    1048626 (0x100032) matched 2
  Press key  left:  * 1113937 (0x10ff51) failed, matched key Q (masked vals tried: 65361 (0xff51), 81 (0x51))
  Press key right:  * 1113939 (0x10ff53) failed, matched key S (masked vals tried: 65363 (0xff53), 83 (0x53))
  Press key   esc:    1048603 (0x10001b) matched esc
```
**That's close enough for me to run the tool, though. Really cool stuff!**

BTW, it works on my OSX 10.10 machine:
```
$ python test_keys.py
Click on the picture and then carefully push the following keys:
  Press key     j:    106 (0x6a) matched j
  Press key     k:    107 (0x6b) matched k
  Press key     J:    74 (0x4a) matched J
  Press key     K:    75 (0x4b) matched K
  Press key     1:    49 (0x31) matched 1
  Press key     2:    50 (0x32) matched 2
  Press key  left:    63234 (0xf702) matched left
  Press key right:    63235 (0xf703) matched right
  Press key   esc:    27 (0x1b) matched esc
```

**Comment by yosinski** [comment]
Hey @lukeyeager, I forgot to push the latest dev version! Can you pull in dev and try again?

**Comment by lukeyeager** [comment]
Works great, thanks!

**Comment by yosinski** [comment]
Glad to hear! It's a shame that keys are so hard to handle with OpenCV. I don't doubt others will have problems with this on their own systems. We'll just have to add new patterns as they arise.

Note for others that may read this later: if you're getting key errors, please run ./test_keys.py and paste the results along with a description of your system (OS + OpenCV version) into a new issue.
