### ISSUE TITLE
Cannot use GPU in CPU-only Caffe: check mode.

### ISSUE THREAD

**Issue by harshmunshi** [yosinski/deep-visualization-toolbox#47]
When I try to run the run_toolbox.py ,CPU mode (which I have done it all along) , get the following error exactly:

F0519 00:48:29.772080 26710 conv_layer.cpp:76] Cannot use GPU in CPU-only Caffe: check mode.

Please help. I cannot locate what to change where.

**Comment by yosinski** [comment]
Have you compiled Caffe in CPU-only mode? That is, with

    CPU_ONLY := 1

in your `Makefile.config`?

**Comment by harshmunshi** [comment]
Hi I followed the instruction again, did the process again but it still gives the same error

**Comment by harshmunshi** [comment]
Hi sorry to waste your time. :(
I'm dumb!

Had to change two files, settings.py and settings_local.py [make the default GPU config to False]
You can mark it solved. :)

**Comment by PHJ007** [comment]
caffevis_mode_gpu = locals().get('caffevis_mode_gpu', True)
Do you mean I need to comment the line of  code? @harshmunshi

**Comment by PHJ007** [comment]
oh,I understand Thanks！ @harshmunshi
