### ISSUE TITLE
trying to compile the deep-vis version of caffe hangs the system!

### ISSUE THREAD

**Issue by Coderx7** [yosinski/deep-visualization-toolbox#54]
When ever I try to compile the deconv-deep-vis-toolbox branch of caffe, it slows down everything to a point where I have to hard-reset the system to get back to the ubunu!. 
I dont have such a problem with the official version of caffe. 
Whats wrong?

**Comment by Coderx7** [comment]
I found the problem, since I have a single core CPU (Intel Pentium G3220), the -j switch made my system hang because it was trying to run the compilation processes in parallel.
removed the -j switch and everything just compiled fine.

**Comment by yosinski** [comment]
Ahh yes, `make -j` can tax one's system. Closing.
