### ISSUE TITLE
Contribute something back to caffe

### ISSUE THREAD

**Issue by bhack** [yosinski/deep-visualization-toolbox#7]
Do you have any plan to contribute some PRs back to caffe?

**Comment by yosinski** [comment]
It's a good idea / question. 

Reasons for:

 - Greater convenience for those using Caffe in that they wouldn't have to clone two repos.

Reasons against:

 - The toolbox allows one to use backprop or deconv, and so for the toolbox not to have to drop features, deconv would have to be added to Caffe as well. However, this would probably add more cruft to Caffe than is worth it (this is why I didn't submit a PR for [my deconv branch](https://github.com/BVLC/caffe/compare/master...yosinski:deconv-deep-vis-toolbox)).
 - Right now the GUI, camera/file interface, and keyboard interface
don't assume Caffe is the backend, so one can actually plug in their own "apps" based on Theano or other frameworks. I had thought this might be useful to people.

What do you think?

**Comment by bhack** [comment]
Yes i talking only for caffe component to no clone you branch. The GUI component will be more useful as indipendent tool  and honestly I think that will become a nightmare to contribute that back knowing review timing and policy :) 
This the actual decovolution in Caffe if you want to take a look http://caffe.berkeleyvision.org/doxygen/classcaffe_1_1DeconvolutionLayer.html
For the GUI It could be simply useful to show how to visualize "your own trained network"

**Comment by yosinski** [comment]
> Yes i talking only for caffe component to no clone you branch. The GUI component will be more useful as indipendent tool and honestly I think that will become a nightmare to contribute that back knowing review timing and policy :)

Is it *that* bad?!? ;)

> This the actual decovolution in Caffe if you want to take a look http://caffe.berkeleyvision.org/doxygen/classcaffe_1_1DeconvolutionLayer.html

I meant that we'd need to add the "deconv" operator, ala [Zeiler's](http://arxiv.org/abs/1311.2901) work, which is more or less equivalent to the existing backprop operator (except the behavior through Relu and LRN layers is different). It's an unfortunate collision of names, but the "deconvolution" layer in Caffe is a different feature.

One merging option would be to let the deep-vis-toolbox mature slightly as a codebase, then consider merging it into caffe later if it becomes popular.

**Comment by bhack** [comment]
@yosinski Oh yes sorry for the second point.. I was really confused with name collision before looking at diff you pointed :)
I still think that the GUI component it is really useful as backend-indipendent tool and I really hope that your caffe fork will not become too soon out of sync :)

**Comment by yosinski** [comment]
> I really hope that your caffe fork will not become too soon out of sync :)

It's a good point. Adding to "reasons for".
