### ISSUE TITLE
backprop pane gray

### ISSUE THREAD

**Issue by elviswind** [yosinski/deep-visualization-toolbox#77]
my backprop pane in the lower left is still gray, even after I set force_backward to true 
actually it's true by default.

**Comment by elviswind** [comment]
![image](https://cloud.githubusercontent.com/assets/2509503/19633121/a8cb8134-99e0-11e6-89ca-028cf9b21233.png)

**Comment by elviswind** [comment]
Sorry, my downloaded weight file is broken. I re-downloaded, and it's ok now

**Comment by Pratyeka** [comment]
Hi，when i use the tool. Back:off and did not plot the deconv image, please give me some help,thank you .

**Comment by YMelon** [comment]
@Pratyeka i have same error, visual my own model and did not plot the deconv image, have you solved this,thank you
