### ISSUE TITLE
deconv visualization 'a' doesn't work

### ISSUE THREAD

**Issue by liuyipei** [yosinski/deep-visualization-toolbox#8]
On my system, the basic visualization of layers, activations, and images work.

When I press 'a', the interface does not crash, but enters a useless state. I get the following message in console:

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/yiliu/deep-visualization-toolbox/caffevis/app.py", line 158, in run
    self.net.backward_from_layer(backprop_layer, diffs, zero_higher = True)
AttributeError: 'Classifier' object has no attribute 'backward_from_layer'

I am on the master branch of caffe. Perhaps you exported more functions locally on your own system?

**Comment by liuyipei** [comment]
should have read instructions

**Comment by PieBoo** [comment]
Hello, how did you do to solve it? :-)
