### ISSUE TITLE
Is it possible to run deep-visualization-toolbox with grayscale images ?

### ISSUE THREAD

**Issue by heybeno** [yosinski/deep-visualization-toolbox#80]
Great toolbox, love it !

I have just a simple query: would it be possible to add a setting so that we can also visualise grayscale models? (e.g. input dim: 1x1x128x128) 

For ex, my top input layer is something like this:
layer {
  name: "data"
  type: "Input"
  top: "data"
  input_param { shape: { dim: 1 dim: 1 dim: 128 dim: 128 } }
  transform_param {
    **force_gray: true**
    scale: 0.00392156862745
  }
}

Much Appreciated,
Ben

**Comment by arikpoz** [comment]
@heybeno
I've added support for grayscale based networks

Latest version is in https://github.com/arikpoz/deep-visualization-toolbox

**Comment by heybeno** [comment]
That is great, thanks. I will check it out !
