### ISSUE TITLE
Data mean = None

### ISSUE THREAD

**Issue by mescarra** [yosinski/deep-visualization-toolbox#92]
Aparently, you could set data mean to `None` (or just avoid setting it at all) at the settings_locale file, and it should be supported by `optimize_image.py`:

> help = '''Mean. The mean may be None, a tuple of one mean value per channel, or a string...""

However, passing a `None` mean, throws a runtime exception on the gradient optimizer constructor since it tries to index the `data_mean` array.

The crash:
```
  File "optimize_image.py", line 222, in <module>
    main()
  File "optimize_image.py", line 194, in main
    channel_swap_to_rgb = channel_swap_to_rgb)
  File "/home/martin/workspace/deep-visualization-toolbox/optimize/gradient_optimizer.py", line 168, in __init__
    self._data_mean_rgb_img = self.data_mean[self.channel_swap_to_rgb].transpose((1,2,0))  # Store as (227,227,3) in RGB order.
TypeError: 'NoneType' object has no attribute '__getitem__'
```

What sould I do?

**Comment by arikpoz** [comment]
@mescarra
I've made the tool substantially more generic: all the hardcoded parts where replaced with new settings parameters, most are deduced automatically by analyzing the network definition file
I've also refactored the use of mean files to support many different input formats

Latest version is in https://github.com/arikpoz/deep-visualization-toolbox
