### ISSUE TITLE
Got key code 255 (0xff), did not match any known key (masked vals tried: 255 (0xff), 255 (0xff))

### ISSUE THREAD

**Issue by JimKlingshirn** [yosinski/deep-visualization-toolbox#95]
cv2::waitKey() is continually returning a value of 255.   The following message repeats forever:

"Got key code 255 (0xff), did not match any known key (masked vals tried: 255 (0xff), 255 (0xff))"

The endlessly repeated key causes the application to behave badly, preventing it from computing and displaying the visualizations.

Ubuntu 16.04, 64 bit
OpenCV 3.2.0

**Comment by JimKlingshirn** [comment]
Successfully working around the problem by not appending keys if they have a value of 255

at line 160 live_vis.py

                 if (key != 255):
                        keys.append(key)

**Comment by clancyian** [comment]
Thanks Jim, spent a good few hours trying to debug this issue.

**Comment by yosinski** [comment]
Merged PR #99; thanks for the fix!
